# Generated by Django 5.2 on 2025-04-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListBooks',
            fields=[
                ('pk', models.CompositePrimaryKey('list_id', 'book_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'list_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('list_id', models.IntegerField(primary_key=True, serialize=False)),
                ('list_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListTypes',
            fields=[
                ('list_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.TextField()),
            ],
            options={
                'db_table': 'list_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NytBestsellers',
            fields=[
                ('nyt_bestsellers_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_nyt', models.DateField()),
                ('ranking', models.IntegerField()),
            ],
            options={
                'db_table': 'nyt_bestsellers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('email', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('date_published', models.CharField(blank=True, max_length=20, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_details',
                'managed': True,
            },
        ),
    ]
